// Defines an interface that our simulation software uses to model the performance of missiles.
public interface MissileSimulator {
	
    // This method should return the mass (in kilograms) of the simulated rocket at a specified time.
    abstract double getMassInKg();

    // This method should return the thrust force (in newtons per second) generated by the simulated missile.
    public double getThrustInNewtonsSec();

    // This method should update the current time based on the current time of the simulation clock.
    void setSimulatedTime(double t);
    
}